'use client';
import {useEffect,useMemo,useState,useSyncExternalStore} from 'react';
import {ArrowUpRight,ArrowRight,CalendarDays,Search,ShieldCheck,Star,SlidersHorizontal,RefreshCw,Info,ExternalLink,ChevronRight,Radio,TriangleAlert} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import {Button} from './ui/button';
import {SiteShell} from './site-shell';
import type {MarketSnapshot,RiskForecast,Simulation,Stock} from '../lib/market-types';
import {forecastDispositionRisk,simulate} from '../lib/rules';
import {fmt,shortDate,ruleNames,displayIntervals} from '../lib/format';
import {readFavorites,subscribeFavorites,parseFavorites,toggleFavorite} from '../lib/favorites';
import {dispositionTier,dispositionTierLabel,type DispositionTier} from '../lib/disposition-tier';
import {loadLatestSnapshot} from '../lib/static-data';
function buildResults(snapshot:MarketSnapshot){return new Map(snapshot.stocks.map(stock=>{try{return [stock.code,simulate(stock,snapshot)] as const;}catch{return [stock.code,undefined] as const;}}));}
type Mode='risk'|'attention'|'disposed'|'watchlist';
export function Dashboard({initial,storage,servedAt}:{initial:MarketSnapshot;storage:string;servedAt:number}){
 const [snapshot,setSnapshot]=useState(initial),[mode,setMode]=useState<Mode>('risk'),[search,setSearch]=useState(''),[market,setMarket]=useState('ALL'),[tier,setTier]=useState<'all'|DispositionTier>('all'),[sort,setSort]=useState('code'),[clock,setClock]=useState(servedAt),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const favoriteJson=useSyncExternalStore(subscribeFavorites,readFavorites,()=> '[]'),favorites=useMemo(()=>parseFavorites(favoriteJson),[favoriteJson]);
 const toggle=(code:string)=>{if(!toggleFavorite(code))setMessage('此瀏覽器無法保存自選股，目前僅在頁面保留。');};
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const activeDisposition=snapshot.dispositions.filter(d=>d.end&&d.end>=snapshot.asOf);
 // The compiler cannot preserve this Map memo; keep expensive rational calculations independent of search keystrokes.
 // eslint-disable-next-line react-hooks/preserve-manual-memoization
 const results=useMemo(()=>buildResults(snapshot),[snapshot]);
 // The risk map performs rolling-window projections and should only rerun for a new snapshot.
 // eslint-disable-next-line react-hooks/preserve-manual-memoization
 const risks=useMemo(()=>new Map(snapshot.stocks.map(s=>[s.code,forecastDispositionRisk(s,snapshot)])),[snapshot]);
 const count={risk:[...risks.values()].filter(Boolean).length,attention:new Set(snapshot.todayNotices.map(n=>n.code)).size,disposed:new Set(activeDisposition.map(d=>d.code)).size,watchlist:favorites.length};
 const list=useMemo(()=>snapshot.stocks.filter(s=>(market==='ALL'||s.market===market)&&(!search||`${s.code}${s.name}`.toLowerCase().includes(search.toLowerCase()))&&(mode==='disposed'||tier==='all'||dispositionTier(s,snapshot.calendar,snapshot.asOf)===tier)&&(mode==='risk'?!!risks.get(s.code):mode==='attention'?s.notices.some(n=>n.date===snapshot.asOf):mode==='disposed'?s.dispositions.some(d=>d.end&&d.end>=snapshot.asOf):favorites.includes(s.code))).sort((a,b)=>{if(mode==='risk'){const day=(risks.get(a.code)?.days||9)-(risks.get(b.code)?.days||9);if(day)return day;const official=Number(!!b.candidateReason)-Number(!!a.candidateReason);if(official)return official;}return sort==='price'?(b.close||0)-(a.close||0):sort==='change'?(b.changePercent||0)-(a.changePercent||0):a.code.localeCompare(b.code);}),[snapshot,market,tier,search,mode,sort,favorites,risks]);
 const focus=list[0],focusRisk=focus?risks.get(focus.code):undefined;
 const refresh=async()=>{setBusy(true);setMessage('正在讀取最新發布快照…');try{const value=await loadLatestSnapshot(snapshot);setSnapshot(value.snapshot);setMessage(value.snapshot.generatedAt===snapshot.generatedAt?'目前已是最新發布批次。':`已更新至 ${value.snapshot.asOf}。`);}catch{setMessage('連線未完成，已保留目前資料。');}finally{setBusy(false);}};
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const abort=new AbortController();void Promise.resolve(ctx.registerTool({name:'filter_stock_watch',title:'篩選處置觀測清單',description:'設定頁面上的股票搜尋與清單類型；不會保存試算或更改自選股。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:40},list:{type:'string',enum:['risk','attention','disposed','watchlist']}},required:['query','list'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const v=input as {query:unknown;list:unknown};if(!v||typeof v.query!=='string'||v.query.length>40||!['risk','attention','disposed','watchlist'].includes(String(v.list)))throw new Error('無效篩選條件');setSearch(v.query);setMode(v.list as Mode);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {query:v.query,list:v.list};}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[]);
 const stale=clock-new Date(`${snapshot.asOf}T16:00:00+08:00`).getTime()>4*86400000;
 return <SiteShell><div className="page-heading"><div><div className="eyebrow">每日盤後・提前理解交易限制</div><h1>三日處置風險<span className="heading-dot">.</span></h1><p>從注意紀錄推估未來三個交易日最早可能達標的時間。</p></div><div className="heading-tools"><div className="date-stamp"><CalendarDays size={18}/><div>資料交易日<strong>{snapshot.asOf.replaceAll('-','.')}</strong></div></div><Button variant="outline" className="refresh-button" disabled={busy} onClick={refresh} aria-label="檢查最新官方資料"><RefreshCw size={15} className={busy?'spin':''}/><span>更新</span></Button></div></div>
 {message&&<p role="status" className="notice-banner"><Info size={16}/>{message}</p>}{(stale||storage==='bundled')&&<p className="notice-banner warning"><TriangleAlert size={16}/>{stale?'目前顯示較早的資料批次，請核對最新官方公告。':'目前使用隨網站發布的快照。'}</p>}
 <div className="summary-grid"><div className="summary-card featured"><div className="summary-label">三日內處置風險 <ArrowUpRight size={18}/></div><div className="summary-number">{String(count.risk).padStart(2,'0')}<span>檔</span></div><p>依最早可能達標日排序，隔日官方候選優先</p></div><div className="summary-card"><div className="summary-label">當日注意普通股 <Radio size={17}/></div><div className="summary-number">{String(count.attention).padStart(2,'0')}<span>檔</span></div><p>已依官方款次整理，供逐筆查閱</p></div><div className="summary-card"><div className="summary-label">處置中／已公告 <ShieldCheck size={18}/></div><div className="summary-number">{String(count.disposed).padStart(2,'0')}<span>檔</span></div><p>實際期間與措施請查看正式公告</p></div></div>
 <div className="dashboard-grid"><section className="panel stock-panel"><div className="panel-heading"><div><h2>股票觀測清單</h2><p>風險區間 <strong>{(snapshot.forecastDates||[snapshot.targetDate,snapshot.effectiveDate])[0]} — {(snapshot.forecastDates||[snapshot.targetDate,snapshot.effectiveDate]).at(-1)}</strong> <span className="separator-dot">·</span> 上市＋上櫃普通股</p></div><span className="badge blue">最快達標優先</span></div><Tabs value={mode} onValueChange={v=>setMode(v as Mode)}><TabsList variant="line" className="stock-tabs"><TabsTrigger value="risk">三日風險 <span>{count.risk}</span></TabsTrigger><TabsTrigger value="attention">今日注意 <span>{count.attention}</span></TabsTrigger><TabsTrigger value="disposed">正式處置 <span>{count.disposed}</span></TabsTrigger><TabsTrigger value="watchlist"><Star size={14}/> 自選股</TabsTrigger></TabsList></Tabs>
 <div className="table-controls"><label className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜尋代號或名稱" aria-label="搜尋股票"/></label><div className="filter-controls"><label><span className="sr-only">市場</span><select value={market} onChange={e=>setMarket(e.target.value)} aria-label="市場"><option value="ALL">全部市場</option><option value="TWSE">上市</option><option value="TPEX">上櫃</option></select></label>{mode!=='disposed'&&<label><span className="sr-only">處置層級</span><select value={tier} onChange={e=>setTier(e.target.value as 'all'|DispositionTier)} aria-label="處置層級"><option value="all">全部層級</option><option value="first">首次處置</option><option value="repeat">再次處置</option></select></label>}<label className="sort-select"><SlidersHorizontal size={15}/><select aria-label="排序方式" value={sort} onChange={e=>setSort(e.target.value)}><option value="code">代號排序</option><option value="price">價格由高至低</option><option value="change">漲幅由高至低</option></select></label></div></div>
 <div className="table-scroll"><table><thead><tr><th className="favorite-cell"><Star size={13}/></th><th>股票</th><th>收盤價／漲跌</th><th>{mode==='disposed'?'處置期間':'下一日條件式價格'}</th><th>{mode==='risk'?'最早風險日／路徑':'注意原因／路徑'}</th><th></th></tr></thead><tbody>{list.map(s=><StockRow key={s.code} stock={s} result={results.get(s.code)} risk={risks.get(s.code)||undefined} saved={favorites.includes(s.code)} toggle={()=>toggle(s.code)} mode={mode} asOf={snapshot.asOf} tier={dispositionTier(s,snapshot.calendar,snapshot.asOf)}/>)}</tbody></table></div>
 {!list.length&&<div className="empty-state"><Search size={28}/><h3>{mode==='watchlist'?'尚未加入自選股':'沒有符合條件的股票'}</h3><p>{mode==='watchlist'?'切換至今日注意，點選股票旁的星號。':'試著修改搜尋內容或切換市場。'}</p><Button variant="outline" onClick={()=>{setSearch('');setMarket('ALL');setMode('attention');}}>查看今日注意股</Button></div>}
 <div className="table-bottom"><span>共 {list.length} 檔 <span className="separator-dot">·</span> 資料截至 {shortDate(snapshot.asOf)}</span><a href="#/methodology">查看計算方式 <ArrowUpRight size={13}/></a></div><div className="panel-note"><Info size={16}/><p>價格區間只代表所選分支在預設情境下成立，仍須滿足量能及除外條件。</p></div><p className="assumption-line">預設假設：市場／同類六日漲跌 0%；市場本益比 30 倍、市場淨值比 2 倍、產業淨值比 3 倍，並非官方平均值。</p></section>
 <aside className="side-column"><section className="focus-card"><div className="side-label"><span className="badge amber">最快風險</span><span>{focusRisk?.official?'官方隔日候選':`第 ${focusRisk?.days||'—'} 個交易日`}</span></div><div className="focus-title"><div><h2>{focus?.name||'目前無風險股'}</h2><span>{focus?.code} · {focus?.market==='TPEX'?'上櫃':'上市'}</span></div><span className="mini-radar"><Radio size={25}/></span></div>{focus&&focusRisk&&<><div className="focus-price">{fmt(focus.close)}<span className={(focus.changePercent||0)>=0?'up':'down'}>{(focus.changePercent||0)>0?'+':''}{fmt(focus.changePercent)}%</span></div><div className="count-track"><div className="count-title"><span>最早可能達標</span><strong>{shortDate(focusRisk.date)}</strong></div><p>{focusRisk.paths.join('、')}</p></div><p className="focus-reason">{focus.candidateReason||'假設後續每個交易日皆再次符合可計次注意條件。'}</p><a className="primary-link" href={`#/stocks/${focus.code}`}>查看價格與必要條件 <ArrowRight size={16}/></a></>}</section><section className="timeline-card"><h3><CalendarDays size={17}/> 三日風險時間軸</h3><ol><li><span className="timeline-node filled"/><div><strong>{shortDate(snapshot.asOf)} 盤後</strong><p>目前注意紀錄</p></div></li>{(snapshot.forecastDates||[snapshot.targetDate,snapshot.effectiveDate]).slice(0,3).map((date,index)=><li key={date}><span className="timeline-node"/><div><strong>{shortDate(date)} 第 {index+1} 日</strong><p>假設再次符合計次注意</p></div></li>)}</ol><a href="#/methodology">了解三日風險的假設 <ChevronRight size={14}/></a></section></aside></div>
 <div className="bottom-insights"><div><ShieldCheck size={20}/><div><strong>官方公告可追溯</strong><p>上市與上櫃候選直接採官方清單。</p></div></div><a href="https://www.twse.com.tw/announcement/notetrans?response=html" target="_blank" rel="noreferrer">上市候選 <ExternalLink size={14}/></a><a href="https://www.tpex.org.tw/zh-tw/announce/market/warning.html" target="_blank" rel="noreferrer">上櫃候選 <ExternalLink size={14}/></a></div>
 </SiteShell>;
}
function StockRow({stock:s,result:r,risk,saved,toggle,mode,asOf,tier}:{stock:Stock;result?:Simulation;risk?:RiskForecast;saved:boolean;toggle:()=>void;mode:Mode;asOf:string;tier:DispositionTier}){
 const item=r?.rules.find(r=>r.rule===6&&r.intervals.length)||r?.rules.find(r=>r.intervals.length), interval=item?.intervals[0],display=item?displayIntervals(item.intervals):[];const notice=s.notices.find(n=>n.date===asOf)||s.notices[0],disposition=s.dispositions.find(d=>d.end&&d.end>=asOf);
 return <tr><td className="favorite-cell"><button aria-label={`${saved?'移除':'加入'}${s.name}自選股`} aria-pressed={saved} className={`star-button ${saved?'saved':''}`} onClick={toggle}><Star size={17} fill={saved?'currentColor':'none'}/></button></td><td><a className="stock-link" href={`#/stocks/${s.code}`}><b>{s.name}</b><small>{s.code} <span>{s.market==='TPEX'?'上櫃':'上市'}</span> <span title={tier==='repeat'?'最近 30 個已知營業日內曾有處置公告':'最近 30 個已知營業日內沒有處置公告'}>{dispositionTierLabel[tier]}</span></small></a></td><td className="number">{fmt(s.close)}<small className={(s.changePercent||0)>=0?'up':'down'}>{(s.changePercent||0)>0?'+':''}{fmt(s.changePercent)}%</small></td><td>{mode==='disposed'&&disposition?<><span className="number">{disposition.start?shortDate(disposition.start):'—'} — {shortDate(disposition.end!)}</span><small>{disposition.measure}</small></>:interval?<><a className="threshold-value" href={`#/stocks/${s.code}`}>{display.map(v=>`${fmt(v.from)}${v.from===v.to?'':` — ${fmt(v.to)}`}`).join(' / ')}</a><small>第{item?.rule}款分支 · 附加條件待滿足</small></>:<><span className="muted">目前無可顯示門檻</span><small>不代表不會處置</small></>}</td><td>{mode==='risk'&&risk?<><span className={`badge ${risk.official?'amber':'blue'}`}>{risk.official?'隔日官方候選':`最快第 ${risk.days} 日`}</span><small>{shortDate(risk.date)} · {risk.paths.join('、')}</small></>:s.candidateReason?<><span className="badge amber">{s.market==='TPEX'?'官方累計候選':r?.gate.paths.join('、')||'官方累計候選'}</span><small>{s.candidateReason}</small></>:<><span className="reason-label">{notice?.rules.map(n=>ruleNames[n]).join('、')||'依官方處置公告'}</span>{mode!=='disposed'&&r&&<small>{s.market==='TPEX'?'歷史累計以官方候選公告為準':`十日 ${r.gate.nineCount}/6 · 三十日 ${r.gate.twentyNineCount}/12`}</small>}</>}</td><td><a className="row-arrow" aria-label={`查看${s.name}明細`} href={`#/stocks/${s.code}`}><ArrowRight size={17}/></a></td></tr>;
}
