'use client';
import {useEffect,useMemo,useState,useSyncExternalStore} from 'react';
import {ArrowUpRight,ArrowRight,CalendarDays,Search,ShieldCheck,Star,SlidersHorizontal,RefreshCw,Info,ExternalLink,ChevronRight,Radio,TriangleAlert} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import {Button} from './ui/button';
import {SiteShell} from './site-shell';
import type {MarketSnapshot,RiskForecast,Simulation,Stock} from '../lib/market-types';
import {forecastDispositionRisk,simulate} from '../lib/rules';
import {fmt,shortDate,ruleNames,displayIntervals} from '../lib/format';
import {readFavorites,subscribeFavorites,parseFavorites,toggleFavorite} from '../lib/favorites';
import {dispositionTier,dispositionTierLabel,type DispositionTier} from '../lib/disposition-tier';
import {loadLatestSnapshot} from '../lib/static-data';
import {isGuaranteedDispositionNextSession} from '../lib/guaranteed-disposition';
function buildResults(snapshot:MarketSnapshot){return new Map(snapshot.stocks.map(stock=>{try{return [stock.code,simulate(stock,snapshot)] as const;}catch{return [stock.code,undefined] as const;}}));}
function OfficialCandidateDot(){return <><span className="official-candidate-dot" role="img" aria-label="官方累計候選" title="官方累計候選"/><span className="badge blue">預計 1 個交易日內</span></>;}
function gateProgress(stock:Stock,calendar:string[],asOf:string){
 const dates=calendar.filter(date=>date<=asOf),noticeDates=new Map(stock.notices.map(notice=>[notice.date,new Set(notice.rules)]));
 const first=(date:string)=>noticeDates.get(date)?.has(1)||false,any=(date:string)=>[...(noticeDates.get(date)||[])].some(rule=>rule>=1&&rule<=8);
 const streak=(matches:(date:string)=>boolean)=>{let count=0;for(const date of [...dates].reverse()){if(!matches(date))break;count++;}return count;};
 return [{label:'連3日',value:streak(first),limit:3},{label:'連5日',value:streak(any),limit:5},{label:'10日',value:dates.slice(-10).filter(any).length,limit:6},{label:'30日',value:dates.slice(-30).filter(any).length,limit:12}];
}
type Mode='risk'|'attention'|'disposed'|'watchlist';
type DashboardSort='default'|'code'|'price'|'change'|'riskDays'|'dispositionEnd'|'notice'|'volume'|'paidInCapital'|'turnover'|'dayTradeRate';
type ProductFilter='ALL'|'YES'|'NO';
function DashboardSortButton({label,field,current,direction,onSort}:{label:string;field:DashboardSort;current:DashboardSort;direction:'asc'|'desc';onSort:(field:DashboardSort)=>void}){const active=current===field;return <button type="button" className="dashboard-sort-header" onClick={()=>onSort(field)} aria-label={`${label}排序${active?`，目前${direction==='asc'?'升冪':'降冪'}`:''}`}>{label}<span aria-hidden="true">{active?(direction==='asc'?'↑':'↓'):'↕'}</span></button>;}
function DashboardMetricHeaders({current,direction,onSort}:{current:DashboardSort;direction:'asc'|'desc';onSort:(field:DashboardSort)=>void}){return <span className="dashboard-metric-headers">{([['成交量','volume'],['股本','paidInCapital'],['週轉率','turnover'],['當沖率','dayTradeRate']] as const).map(([label,field])=><DashboardSortButton key={field} label={label} field={field} current={current} direction={direction} onSort={onSort}/>)}</span>;}
export function Dashboard({initial,storage,servedAt}:{initial:MarketSnapshot;storage:string;servedAt:number}){
 const [snapshot,setSnapshot]=useState(initial),[mode,setMode]=useState<Mode>('risk'),[search,setSearch]=useState(''),[market,setMarket]=useState('ALL'),[tier,setTier]=useState<'all'|DispositionTier>('all'),[stockFutures,setStockFutures]=useState<ProductFilter>('ALL'),[warrants,setWarrants]=useState<ProductFilter>('ALL'),[convertibleBonds,setConvertibleBonds]=useState<ProductFilter>('ALL'),[sort,setSort]=useState<DashboardSort>('default'),[sortDirection,setSortDirection]=useState<'asc'|'desc'>('asc'),[clock,setClock]=useState(servedAt),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const productCoverage=snapshot.productCoverage||{};
 const favoriteJson=useSyncExternalStore(subscribeFavorites,readFavorites,()=> '[]'),favorites=useMemo(()=>parseFavorites(favoriteJson),[favoriteJson]);
 const toggle=(code:string)=>{if(!toggleFavorite(code))setMessage('此瀏覽器無法保存自選股，目前僅在頁面保留。');};
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const activeDisposition=snapshot.dispositions.filter(d=>d.end&&d.end>=snapshot.asOf);
 // The compiler cannot preserve this Map memo; keep expensive rational calculations independent of search keystrokes.
 const results=useMemo(()=>buildResults(snapshot),[snapshot]);
 // The risk map performs rolling-window projections and should only rerun for a new snapshot.
 const risks=useMemo(()=>new Map(snapshot.stocks.map(s=>[s.code,forecastDispositionRisk(s,snapshot)])),[snapshot]);
 const count={risk:[...risks.values()].filter(Boolean).length,attention:new Set(snapshot.todayNotices.map(n=>n.code)).size,disposed:new Set(activeDisposition.map(d=>d.code)).size,watchlist:favorites.length};
 const chooseSort=(field:DashboardSort)=>{if(sort===field)setSortDirection(value=>value==='asc'?'desc':'asc');else{setSort(field);setSortDirection(field==='default'||field==='code'?'asc':'desc');}};
 const list=useMemo(()=>snapshot.stocks.filter(s=>{
  const product=(value:boolean|null|undefined,filter:ProductFilter)=>filter==='ALL'||(filter==='YES'?value===true:value===false);
  return (market==='ALL'||s.market===market)&&(!search||`${s.code}${s.name}`.toLowerCase().includes(search.toLowerCase()))
   &&(mode==='disposed'||tier==='all'||dispositionTier(s,snapshot.calendar,snapshot.asOf)===tier)
   &&(productCoverage.stockFutures!==true||product(s.hasStockFutures,stockFutures))&&(productCoverage.warrants!==true||product(s.hasWarrants,warrants))&&(productCoverage.convertibleBonds!==true||product(s.hasConvertibleBonds,convertibleBonds))
   &&(mode==='risk'?!!risks.get(s.code):mode==='attention'?s.notices.some(n=>n.date===snapshot.asOf):mode==='disposed'?s.dispositions.some(d=>d.end&&d.end>=snapshot.asOf):favorites.includes(s.code));
 }).sort((a,b)=>{
  if(sort==='default'&&mode==='risk'){const day=(risks.get(a.code)?.days||9)-(risks.get(b.code)?.days||9);if(day)return day;const official=Number(!!b.candidateReason)-Number(!!a.candidateReason);if(official)return official;}
  const stockValue=(stock:Stock)=>sort==='code'?stock.code:sort==='price'?stock.close:sort==='change'?stock.changePercent:sort==='volume'?stock.volume:sort==='paidInCapital'?stock.paidInCapital:sort==='turnover'&&stock.volume!=null&&stock.issuedShares?stock.volume/stock.issuedShares*100:sort==='dayTradeRate'&&stock.volume&&stock.dayTradeShares!=null?stock.dayTradeShares/stock.volume*100:sort==='riskDays'?risks.get(stock.code)?.days:sort==='dispositionEnd'?stock.dispositions.find(d=>d.end&&d.end>=snapshot.asOf)?.end:sort==='notice'?(stock.candidateReason||stock.notices.find(n=>n.date===snapshot.asOf)?.reason||''):null;
  const left=stockValue(a),right=stockValue(b);let result=0;
  if(typeof left==='number'&&typeof right==='number')result=left-right;else if(typeof left==='string'&&typeof right==='string')result=left.localeCompare(right,'zh-TW',{numeric:true});else if(left==null||right==null)result=left==null?(right==null?0:1):-1;
  if(result)return sortDirection==='asc'?result:-result;
  return a.code.localeCompare(b.code,'zh-TW',{numeric:true});
 }),[snapshot,market,tier,search,mode,sort,sortDirection,favorites,risks,stockFutures,warrants,convertibleBonds,productCoverage.stockFutures,productCoverage.warrants,productCoverage.convertibleBonds]);
 const focus=list[0],focusRisk=focus?risks.get(focus.code):undefined;
 const refresh=async()=>{setBusy(true);setMessage('正在讀取最新發布快照…');try{const value=await loadLatestSnapshot(snapshot);setSnapshot(value.snapshot);setMessage(value.snapshot.generatedAt===snapshot.generatedAt?'目前已是最新發布批次。':`已更新至 ${value.snapshot.asOf}。`);}catch{setMessage('連線未完成，已保留目前資料。');}finally{setBusy(false);}};
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const abort=new AbortController();void Promise.resolve(ctx.registerTool({name:'filter_stock_watch',title:'篩選處置觀測清單',description:'設定頁面上的股票搜尋與清單類型；不會保存試算或更改自選股。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:40},list:{type:'string',enum:['risk','attention','disposed','watchlist']}},required:['query','list'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const v=input as {query:unknown;list:unknown};if(!v||typeof v.query!=='string'||v.query.length>40||!['risk','attention','disposed','watchlist'].includes(String(v.list)))throw new Error('無效篩選條件');setSearch(v.query);setMode(v.list as Mode);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {query:v.query,list:v.list};}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[]);
 const stale=clock-new Date(`${snapshot.asOf}T16:00:00+08:00`).getTime()>4*86400000;
 const projected=snapshot.stocks.filter(stock=>risks.get(stock.code)).sort((a,b)=>(risks.get(a.code)?.days||9)-(risks.get(b.code)?.days||9));
 const firstProjected=projected.filter(stock=>dispositionTier(stock,snapshot.calendar,snapshot.asOf)==='first').slice(0,4),repeatProjected=projected.filter(stock=>dispositionTier(stock,snapshot.calendar,snapshot.asOf)==='repeat').slice(0,4);
 const nextSession=projected.filter(stock=>risks.get(stock.code)?.days===1).slice(0,8);
 const announcedCodes=[...new Set(snapshot.todayNotices.map(notice=>notice.code))].slice(0,8),announced=snapshot.stocks.filter(stock=>announcedCodes.includes(stock.code));
 const exits=[...new Map(activeDisposition.filter(d=>d.end).sort((a,b)=>a.end!.localeCompare(b.end!)).map(d=>[d.code,d])).values()].slice(0,12);
 return <SiteShell><div className="page-heading"><div><div className="eyebrow">上市・上櫃每日盤後觀測</div><h1>注意股<span className="heading-dot">.</span></h1><p>查看官方注意名單，並依可能達到處置門檻的先後順序觀察。</p></div><div className="heading-tools"><div className="date-stamp"><CalendarDays size={18}/><div>資料交易日<strong>{snapshot.asOf.replaceAll('-','.')}</strong></div></div><Button variant="outline" className="refresh-button" disabled={busy} onClick={refresh} aria-label="檢查最新官方資料"><RefreshCw size={15} className={busy?'spin':''}/><span>更新</span></Button></div></div>
 {message&&<p role="status" className="notice-banner"><Info size={16}/>{message}</p>}{(stale||storage==='bundled')&&<p className="notice-banner warning"><TriangleAlert size={16}/>{stale?'目前顯示較早的資料批次，請核對最新官方公告。':'目前使用隨網站發布的快照。'}</p>}
 <div className="summary-grid"><div className="summary-card featured"><div className="summary-label">注意股風險觀測 <ArrowUpRight size={18}/></div><div className="summary-number">{String(count.risk).padStart(2,'0')}<span>檔</span></div><p>依可能達到處置門檻的先後順序排列</p></div><div className="summary-card"><div className="summary-label">當日注意普通股 <Radio size={17}/></div><div className="summary-number">{String(count.attention).padStart(2,'0')}<span>檔</span></div><p>已依官方款次整理，供逐筆查閱</p></div><div className="summary-card"><div className="summary-label">處置中／已公告 <ShieldCheck size={18}/></div><div className="summary-number">{String(count.disposed).padStart(2,'0')}<span>檔</span></div><p>實際期間與措施請查看正式公告</p></div></div>
 <section className="insight-grid" aria-label="風險與公告摘要">
  <article className="insight-card"><h2><span className="insight-icon first">首</span>首次處置預測 <small>{firstProjected.length}</small></h2><div className="insight-stock-list">{firstProjected.length?firstProjected.map(stock=><a href={`#/stocks/${stock.code}`} key={stock.code}><strong>{stock.code}</strong> {stock.name}<small>{risks.get(stock.code)?.paths.join('、')}</small></a>):<p className="insight-empty">目前沒有符合的預測項目</p>}</div></article>
  <article className="insight-card"><h2><span className="insight-icon repeat">再</span>再次處置預測 <small>{repeatProjected.length}</small></h2><div className="insight-stock-list">{repeatProjected.length?repeatProjected.map(stock=><a href={`#/stocks/${stock.code}`} key={stock.code}><strong>{stock.code}</strong> {stock.name}<small>{risks.get(stock.code)?.paths.join('、')}</small></a>):<p className="insight-empty">目前沒有符合的預測項目</p>}</div></article>
  <article className="insight-card insight-wide"><h2><span className="insight-icon urgent">!</span>近期可能達標名單 <small>{nextSession.length}</small></h2><div className="insight-chips">{nextSession.length?nextSession.map(stock=><a href={`#/stocks/${stock.code}`} key={stock.code}><strong>{stock.code}</strong> {stock.name} · {dispositionTierLabel[dispositionTier(stock,snapshot.calendar,snapshot.asOf)]}</a>):<p className="insight-empty">目前沒有隔日可能達標項目</p>}</div></article>
  <article className="insight-card"><h2><span className="insight-icon notices">$</span>今日注意公告 <small>{announced.length}</small></h2><div className="insight-stock-list">{announced.length?announced.slice(0,5).map(stock=>{const notice=snapshot.todayNotices.find(item=>item.code===stock.code);return <a href={`#/stocks/${stock.code}`} key={stock.code}><strong>{stock.code}</strong> {stock.name}<small>{notice?.rules.map(rule=>ruleNames[rule]).join('、')||'官方注意交易資訊'}</small></a>}):<p className="insight-empty">資料日沒有注意公告</p>}</div></article>
  <article className="insight-card"><h2><span className="insight-icon exits">✓</span>近期出關 <small>{exits.length}</small></h2><div className="exit-stock-list">{exits.length?exits.map(item=>{const stock=snapshot.stocks.find(s=>s.code===item.code);return <a href={`#/stocks/${item.code}`} key={item.code}><strong>{shortDate(item.end!)}</strong><span>{item.code} {stock?.name||item.name}</span></a>}):<p className="insight-empty">目前沒有處置中股票</p>}</div></article>
 </section>
 <div className={`dashboard-grid ${mode!=='risk'?'expanded-stock-grid':''}`}><section className="panel stock-panel"><div className="panel-heading"><div><h2>注意股清單</h2><p>可能達標觀測區間 <strong>{(snapshot.forecastDates||[snapshot.targetDate,snapshot.effectiveDate])[0]} — {(snapshot.forecastDates||[snapshot.targetDate,snapshot.effectiveDate]).at(-1)}</strong> <span className="separator-dot">·</span> 上市＋上櫃普通股</p></div><span className="badge blue">依最早達標日排序</span></div><Tabs value={mode} onValueChange={v=>setMode(v as Mode)}><TabsList variant="line" className="stock-tabs"><TabsTrigger value="risk">風險觀測 <span>{count.risk}</span></TabsTrigger><TabsTrigger value="attention">今日注意 <span>{count.attention}</span></TabsTrigger><TabsTrigger value="disposed">正式處置 <span>{count.disposed}</span></TabsTrigger><TabsTrigger value="watchlist"><Star size={14}/> 自選股</TabsTrigger></TabsList></Tabs>
 <div className="table-controls"><label className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜尋代號或名稱" aria-label="搜尋股票"/></label><div className="filter-controls"><label><span className="sr-only">市場</span><select value={market} onChange={e=>setMarket(e.target.value)} aria-label="市場"><option value="ALL">全部市場</option><option value="TWSE">上市</option><option value="TPEX">上櫃</option></select></label>{mode!=='disposed'&&<label><span className="sr-only">處置層級</span><select value={tier} onChange={e=>setTier(e.target.value as 'all'|DispositionTier)} aria-label="處置層級"><option value="all">全部層級</option><option value="first">首次處置</option><option value="repeat">再次處置</option></select></label>}<label><span className="sr-only">有股期</span><select disabled={productCoverage.stockFutures!==true} value={stockFutures} onChange={e=>setStockFutures(e.target.value as ProductFilter)} aria-label="有股期"><option value="ALL">{productCoverage.stockFutures===true?'股期不限':'股期待資料'}</option><option value="YES">有股期</option><option value="NO">無股期</option></select></label><label><span className="sr-only">有權證</span><select disabled={productCoverage.warrants!==true} value={warrants} onChange={e=>setWarrants(e.target.value as ProductFilter)} aria-label="有權證"><option value="ALL">{productCoverage.warrants===true?'權證不限':'權證待資料'}</option><option value="YES">有權證</option><option value="NO">無權證</option></select></label><label><span className="sr-only">有 CB</span><select disabled={productCoverage.convertibleBonds!==true} value={convertibleBonds} onChange={e=>setConvertibleBonds(e.target.value as ProductFilter)} aria-label="有 CB"><option value="ALL">{productCoverage.convertibleBonds===true?'CB 不限':'CB 待資料'}</option><option value="YES">有 CB</option><option value="NO">無 CB</option></select></label><label className="sort-select"><SlidersHorizontal size={15}/><select aria-label="排序方式" value={sort} onChange={e=>{setSort(e.target.value as DashboardSort);setSortDirection('asc');}}><option value="default">預設排序</option><option value="code">代號</option><option value="price">收盤價</option><option value="change">當日漲跌</option><option value="riskDays">風險日</option><option value="dispositionEnd">出關日</option><option value="volume">成交量</option><option value="paidInCapital">股本</option><option value="turnover">週轉率</option><option value="dayTradeRate">當沖率</option></select></label></div></div>
 <div className="table-scroll"><table className={mode==='risk'?'risk-table':''}><thead>{mode==='risk'?<tr><th><DashboardSortButton label="股票" field="code" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardSortButton label="收盤價" field="price" current={sort} direction={sortDirection} onSort={chooseSort}/> / <DashboardSortButton label="漲跌" field="change" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardSortButton label="最早風險日／路徑" field="riskDays" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardMetricHeaders current={sort} direction={sortDirection} onSort={chooseSort}/></th><th></th></tr>:<tr><th className="favorite-cell"><DashboardSortButton label="☆" field="code" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardSortButton label="股票" field="code" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardSortButton label="收盤價" field="price" current={sort} direction={sortDirection} onSort={chooseSort}/> / <DashboardSortButton label="漲跌" field="change" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardSortButton label={mode==='disposed'?'處置期間':'條件式價格'} field={mode==='disposed'?'dispositionEnd':'riskDays'} current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardSortButton label="注意原因／路徑" field="notice" current={sort} direction={sortDirection} onSort={chooseSort}/></th><th><DashboardMetricHeaders current={sort} direction={sortDirection} onSort={chooseSort}/></th><th></th></tr>}</thead><tbody>{list.map(s=><StockRow key={s.code} stock={s} result={results.get(s.code)} risk={risks.get(s.code)||undefined} saved={favorites.includes(s.code)} toggle={()=>toggle(s.code)} mode={mode} asOf={snapshot.asOf} tier={dispositionTier(s,snapshot.calendar,snapshot.asOf)} calendar={snapshot.calendar}/>)}</tbody></table></div>
 {!list.length&&<div className="empty-state"><Search size={28}/><h3>{mode==='watchlist'?'尚未加入自選股':'沒有符合條件的股票'}</h3><p>{mode==='watchlist'?'切換至今日注意，點選股票旁的星號。':'試著修改搜尋內容或切換市場。'}</p><Button variant="outline" onClick={()=>{setSearch('');setMarket('ALL');setMode('attention');}}>查看今日注意股</Button></div>}
 <div className="table-bottom"><span>共 {list.length} 檔 <span className="separator-dot">·</span> 資料截至 {shortDate(snapshot.asOf)}</span><a href="#/methodology">查看計算方式 <ArrowUpRight size={13}/></a></div><div className="panel-note"><Info size={16}/><p>週轉率＝成交股數 ÷ 已發行普通股數；當沖率＝當日沖銷成交股數 ÷ 成交股數。股本採官方實收資本額，缺漏資料顯示「—」。</p></div><p className="assumption-line">預設假設：市場／同類六日漲跌 0%；市場本益比 30 倍、市場淨值比 2 倍、產業淨值比 3 倍，並非官方平均值。</p></section>
 <aside className="side-column"><section className="focus-card"><div className="side-label"><span className="badge amber">優先觀察</span><span>{focusRisk?.official?'官方處置候選':`最快第 ${focusRisk?.days||'—'} 個交易日`}</span></div><div className="focus-title"><div><h2>{focus?.name||'目前無風險股'}</h2><span>{focus?.code} · {focus?.market==='TPEX'?'上櫃':'上市'}</span></div><span className="mini-radar"><Radio size={25}/></span></div>{focus&&focusRisk&&<><div className="focus-price">{fmt(focus.close)}<span className={(focus.changePercent||0)>=0?'up':'down'}>{(focus.changePercent||0)>0?'+':''}{fmt(focus.changePercent)}%</span></div><div className="count-track"><div className="count-title"><span>最早可能達標</span><strong>{shortDate(focusRisk.date)}</strong></div><p>{focusRisk.paths.join('、')}</p></div><p className="focus-reason">{focus.candidateReason||'假設後續每個交易日皆再次符合可計次注意條件。'}</p><a className="primary-link" href={`#/stocks/${focus.code}`}>查看價格與必要條件 <ArrowRight size={16}/></a></>}</section><section className="timeline-card"><h3><CalendarDays size={17}/> 可能達標時間</h3><ol><li><span className="timeline-node filled"/><div><strong>{shortDate(snapshot.asOf)} 盤後</strong><p>目前注意紀錄</p></div></li>{(snapshot.forecastDates||[snapshot.targetDate,snapshot.effectiveDate]).slice(0,3).map((date,index)=><li key={date}><span className="timeline-node"/><div><strong>{shortDate(date)} · 第 {index+1} 個交易日</strong><p>假設再次符合計次注意</p></div></li>)}</ol><a href="#/methodology">了解風險觀測方式 <ChevronRight size={14}/></a></section></aside></div>
 <div className="bottom-insights"><div><ShieldCheck size={20}/><div><strong>官方公告可追溯</strong><p>上市與上櫃候選直接採官方清單。</p></div></div><a href="https://www.twse.com.tw/announcement/notetrans?response=html" target="_blank" rel="noreferrer">上市候選 <ExternalLink size={14}/></a><a href="https://www.tpex.org.tw/zh-tw/announce/market/warning.html" target="_blank" rel="noreferrer">上櫃候選 <ExternalLink size={14}/></a></div>
 </SiteShell>;
}
function StockRow({stock:s,result:r,risk,saved,toggle,mode,asOf,tier,calendar}:{stock:Stock;result?:Simulation;risk?:RiskForecast;saved:boolean;toggle:()=>void;mode:Mode;asOf:string;tier:DispositionTier;calendar:string[]}){
 const item=r?.rules.find(r=>r.rule===6&&r.intervals.length)||r?.rules.find(r=>r.intervals.length), interval=item?.intervals[0],display=item?displayIntervals(item.intervals):[];const notice=s.notices.find(n=>n.date===asOf)||s.notices[0],disposition=s.dispositions.find(d=>d.end&&d.end>=asOf);
 const guaranteed=risk?.days===1&&isGuaranteedDispositionNextSession(s,r);
 const gates=r?gateProgress(s,calendar,asOf):[];
 const historyReady=s.noticeHistoryComplete===true;
 const progress=<div className="gate-progress">{gates.map(gate=><div className="gate-progress-item" key={gate.label} aria-label={`${gate.label} ${historyReady?`${gate.value}/${gate.limit}`:'資料待補'}`}><span>{gate.label}</span><div><i style={{width:historyReady?`${Math.min(100,gate.value/gate.limit*100)}%`:'0%'}}/></div><b>{historyReady?`${gate.value}/${gate.limit}`:'—'}</b></div>)}</div>;
 const turnoverPct=s.volume!==null&&s.issuedShares!=null&&s.issuedShares>0?s.volume/s.issuedShares*100:null;
 const dayTradePct=s.volume!==null&&s.volume>0&&s.dayTradeShares!=null?s.dayTradeShares/s.volume*100:null;
 const metrics=<div className="stock-metrics-grid"><div><small>成交量</small><strong>{s.volume===null?'—':`${fmt(s.volume/1000,0)} 張`}</strong></div><div><small>股本</small><strong>{s.paidInCapital==null?'—':`${fmt(s.paidInCapital/100000000,2)} 億`}</strong></div><div><small>週轉率</small><strong>{turnoverPct===null?'—':`${fmt(turnoverPct,2)}%`}</strong></div><div><small>當沖率</small><strong>{dayTradePct===null?'—':`${fmt(dayTradePct,2)}%`}</strong></div></div>;
 if(mode==='risk')return <tr className="risk-stock-row"><td className="risk-stock-cell"><button aria-label={`${saved?'移除':'加入'}${s.name}自選股`} aria-pressed={saved} className={`star-button ${saved?'saved':''}`} onClick={toggle}><Star size={17} fill={saved?'currentColor':'none'}/></button><a className="risk-stock-link" href={`#/stocks/${s.code}`}><b>{s.code}</b><span>{s.name}</span><small>{s.market==='TPEX'?'上櫃':'上市'}</small></a></td><td className="risk-price-cell number">{fmt(s.close)}<small className={(s.changePercent||0)>=0?'up':'down'}>{(s.changePercent||0)>0?'+':''}{fmt(s.changePercent)}%</small></td><td className="risk-projection-cell"><div className="risk-projection-heading"><div className="risk-badges">{risk?.official?<OfficialCandidateDot/>:<span className="badge blue">預計 {risk?.days||'—'} 個交易日內</span>}{guaranteed&&<span className="badge must-close-badge" title="僅限一個交易日內可能達標，且各合法漲跌停價格均符合已支援的第一款條件。">必關股</span>}</div>{!risk?.official&&<strong>最早預測達標日 {risk?shortDate(risk.date):'—'}</strong>}<a href={`#/stocks/${s.code}`}>{risk?.official?s.candidateReason||'':risk?.paths.join('、')||s.candidateReason||'查看注意條件'}</a></div>{progress}</td><td className="risk-metrics-cell">{metrics}</td><td className="risk-detail-cell"><a className="row-arrow" aria-label={`查看${s.name}明細`} href={`#/stocks/${s.code}`}><ArrowRight size={17}/></a></td></tr>;
 return <tr><td className="favorite-cell"><button aria-label={`${saved?'移除':'加入'}${s.name}自選股`} aria-pressed={saved} className={`star-button ${saved?'saved':''}`} onClick={toggle}><Star size={17} fill={saved?'currentColor':'none'}/></button></td><td><a className="stock-link" href={`#/stocks/${s.code}`}><b>{s.name}</b><small>{s.code} <span>{s.market==='TPEX'?'上櫃':'上市'}</span> <span title={tier==='repeat'?'最近 30 個已知營業日內曾有處置公告':'最近 30 個已知營業日內沒有處置公告'}>{dispositionTierLabel[tier]}</span></small></a></td><td className="number">{fmt(s.close)}<small className={(s.changePercent||0)>=0?'up':'down'}>{(s.changePercent||0)>0?'+':''}{fmt(s.changePercent)}%</small></td><td>{mode==='disposed'&&disposition?<><span className="number">{disposition.start?shortDate(disposition.start):'—'} — {shortDate(disposition.end!)}</span><small>{disposition.measure}</small></>:interval?<><a className="threshold-value" href={`#/stocks/${s.code}`}>{display.map(v=>`${fmt(v.from)}${v.from===v.to?'':` — ${fmt(v.to)}`}`).join(' / ')}</a><small>第{item?.rule}款分支 · 附加條件待滿足</small></>:<><span className="muted">目前無可顯示門檻</span><small>不代表不會處置</small></>}</td><td>{s.candidateReason?<><OfficialCandidateDot/>{guaranteed&&<span className="badge must-close-badge" title="僅限一個交易日內可能達標，且各合法漲跌停價格均符合已支援的第一款條件。">必關股</span>}<small>{s.candidateReason}</small>{mode==='attention'&&progress}</>:<><span className="reason-label">{notice?.rules.map(n=>ruleNames[n]).join('、')||'依官方處置公告'}</span>{mode==='attention'&&progress}{r&&<small>{s.market==='TPEX'?'歷史累計以官方候選公告為準':`十日 ${r.gate.nineCount}/6 · 三十日 ${r.gate.twentyNineCount}/12`}</small>}</>}</td><td className="stock-extra-metrics">{metrics}</td><td><a className="row-arrow" aria-label={`查看${s.name}明細`} href={`#/stocks/${s.code}`}><ArrowRight size={17}/></a></td></tr>;
}
