import {useMemo,useState} from 'react';
import {ArrowDownWideNarrow,Filter,Search,SlidersHorizontal} from 'lucide-react';
import type {ScreenerSnapshot} from '../lib/market-types';
import {fmt,shortDate} from '../lib/format';
import {industryName} from '../lib/industry';
import {buildScreenRows,screenStocks,type ScreenSort,type SortDirection} from '../lib/stock-screen';
import {SiteShell} from './site-shell';

const price=(value:number|null)=>value===null?'—':fmt(value,2);
const pct=(value:number|null)=>value===null?'資料不足':`${value>0?'+':''}${fmt(value,2)}%`;

function SortHeader({label,field,current,direction,onSort}:{label:string;field:ScreenSort;current:ScreenSort;direction:SortDirection;onSort:(field:ScreenSort)=>void}){
 const active=current===field;
 return <th aria-sort={active?direction==='asc'?'ascending':'descending':'none'}><button type="button" className="screener-sort-header" onClick={()=>onSort(field)}>{label}<span aria-hidden="true">{active?(direction==='asc'?'↑':'↓'):'↕'}</span></button></th>;
}

export function StockScreener({snapshot,notice}:{snapshot:ScreenerSnapshot;notice?:string}){
 const [query,setQuery]=useState(''),[market,setMarket]=useState('ALL'),[industry,setIndustry]=useState('ALL'),[stockFutures,setStockFutures]=useState('ALL'),[warrants,setWarrants]=useState('ALL'),[convertibleBonds,setConvertibleBonds]=useState('ALL'),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[minChangeToday,setMinChangeToday]=useState(''),[maxChangeToday,setMaxChangeToday]=useState(''),[minChange30,setMinChange30]=useState(''),[maxChange30,setMaxChange30]=useState(''),[minVolume,setMinVolume]=useState(''),[minTurnover,setMinTurnover]=useState(''),[sort,setSort]=useState<ScreenSort>('change30'),[sortDirection,setSortDirection]=useState<SortDirection>('desc');
 const rows=useMemo(()=>buildScreenRows(snapshot),[snapshot]);
 const productCoverage=snapshot.productCoverage||{};
 const industries=useMemo(()=>[...new Set(rows.map(({stock})=>stock.industry?.trim()).filter((value):value is string=>Boolean(value)))].sort((a,b)=>industryName(a).localeCompare(industryName(b),'zh-TW')),[rows]);
 const filtered=useMemo(()=>screenStocks(rows,{query,market,industry,stockFutures,warrants,convertibleBonds,minPrice,maxPrice,minChangeToday,maxChangeToday,minChange30,maxChange30,minVolume,minTurnover},sort,sortDirection),[rows,query,market,industry,stockFutures,warrants,convertibleBonds,minPrice,maxPrice,minChangeToday,maxChangeToday,minChange30,maxChange30,minVolume,minTurnover,sort,sortDirection]);
 const chooseSort=(field:ScreenSort)=>{if(field===sort)setSortDirection(value=>value==='desc'?'asc':'desc');else{setSort(field);setSortDirection('desc');}};
 const reset=()=>{setQuery('');setMarket('ALL');setIndustry('ALL');setStockFutures('ALL');setWarrants('ALL');setConvertibleBonds('ALL');setMinPrice('');setMaxPrice('');setMinChangeToday('');setMaxChangeToday('');setMinChange30('');setMaxChange30('');setMinVolume('');setMinTurnover('');setSort('change30');setSortDirection('desc');};
 const enough30=rows.filter(row=>row.change30!==null).length;
 return <SiteShell active="screener">
  <div className="page-heading"><div><div className="eyebrow">MARKET-WIDE STOCK SCREEN</div><h1>股票篩選<span className="heading-dot">.</span></h1><p>依交易日收盤資料篩選上市與上櫃普通股；漲跌幅以累積價格變化計算。</p></div><div className="date-stamp"><ArrowDownWideNarrow size={18}/><div>資料交易日<strong>{snapshot.asOf.replaceAll('-','.')}</strong></div></div></div>
  {notice&&<p role="status" className="notice-banner warning">{notice} 目前先顯示快照中可用的股票；正式全市場資料會在更新批次完成後載入。</p>}
  <div className="summary-grid screener-summary"><div className="summary-card featured"><div className="summary-label">符合目前條件 <Filter size={16}/></div><div className="summary-number">{filtered.length}<span>檔</span></div><p>可依價格、漲跌幅、成交量與週轉率組合篩選</p></div><div className="summary-card"><div className="summary-label">目前資料股票</div><div className="summary-number">{rows.length}<span>檔</span></div><p>上市與上櫃普通股行情快照</p></div><div className="summary-card"><div className="summary-label">具備完整 30 日漲跌資料</div><div className="summary-number">{enough30}<span>檔</span></div><p>需要至少 31 個有效收盤價；不足者標示資料不足</p></div></div>
  <section className="panel screener-panel"><div className="panel-heading"><div><h2>設定篩選條件</h2><p>所有門檻均為選填；漲跌幅為最近 30／10／5 個交易日的首尾收盤價差。</p></div><button className="screener-reset" type="button" onClick={reset}>清除條件</button></div>
    <div className="screener-filters"><label className="screener-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="股票代號或名稱" aria-label="股票代號或名稱"/></label><label><span>市場</span><select value={market} onChange={event=>setMarket(event.target.value)}><option value="ALL">全部市場</option><option value="TWSE">上市</option><option value="TPEX">上櫃</option></select></label><label><span>產業族群</span><select value={industry} onChange={event=>setIndustry(event.target.value)}><option value="ALL">全部產業</option>{industries.map(value=><option key={value} value={value}>{industryName(value)}</option>)}<option value="__UNCLASSIFIED__">未分類</option></select></label><label><span>有股期{productCoverage.stockFutures===true?'':'（待資料）'}</span><select disabled={productCoverage.stockFutures!==true} value={stockFutures} onChange={event=>setStockFutures(event.target.value)}><option value="ALL">不限</option><option value="YES">有</option><option value="NO">無</option></select></label><label><span>有權證{productCoverage.warrants===true?'':'（待資料）'}</span><select disabled={productCoverage.warrants!==true} value={warrants} onChange={event=>setWarrants(event.target.value)}><option value="ALL">不限</option><option value="YES">有</option><option value="NO">無</option></select></label><label><span>有 CB{productCoverage.convertibleBonds===true?'':'（待資料）'}</span><select disabled={productCoverage.convertibleBonds!==true} value={convertibleBonds} onChange={event=>setConvertibleBonds(event.target.value)}><option value="ALL">不限</option><option value="YES">有</option><option value="NO">無</option></select></label><label><span>最低價格</span><input type="number" min="0" step="0.01" value={minPrice} onChange={event=>setMinPrice(event.target.value)} placeholder="不限"/></label><label><span>最高價格</span><input type="number" min="0" step="0.01" value={maxPrice} onChange={event=>setMaxPrice(event.target.value)} placeholder="不限"/></label><label><span>當日漲跌下限 %</span><input type="number" step="0.1" value={minChangeToday} onChange={event=>setMinChangeToday(event.target.value)} placeholder="不限"/></label><label><span>當日漲跌上限 %</span><input type="number" step="0.1" value={maxChangeToday} onChange={event=>setMaxChangeToday(event.target.value)} placeholder="不限"/></label><label><span>30 日漲幅下限 %</span><input type="number" step="0.1" value={minChange30} onChange={event=>setMinChange30(event.target.value)} placeholder="不限"/></label><label><span>30 日漲幅上限 %</span><input type="number" step="0.1" value={maxChange30} onChange={event=>setMaxChange30(event.target.value)} placeholder="不限"/></label><label><span>成交量下限 張</span><input type="number" min="0" step="1" value={minVolume} onChange={event=>setMinVolume(event.target.value)} placeholder="不限"/></label><label><span>週轉率下限 %</span><input type="number" min="0" step="0.1" value={minTurnover} onChange={event=>setMinTurnover(event.target.value)} placeholder="不限"/></label></div>
    <div className="screener-result-bar"><span><SlidersHorizontal size={15}/> {filtered.length} 檔符合</span><label>排序<select value={sort} onChange={event=>{setSort(event.target.value as ScreenSort);setSortDirection('desc');}}><option value="code">股票代號</option><option value="industry">產業族群</option><option value="price">收盤價</option><option value="changeToday">當日漲跌</option><option value="change5">5 日漲跌</option><option value="change10">10 日漲跌</option><option value="change30">30 日漲跌</option><option value="volume">成交量</option><option value="turnover">週轉率</option><option value="ma20">20MA 乖離</option></select></label><span className="screener-sort-hint">點擊表格標頭可切換排序方向</span></div>
   <div className="table-scroll"><table className="screener-table"><thead><tr><SortHeader label="股票" field="code" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="產業族群" field="industry" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="收盤價" field="price" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="當日漲跌" field="changeToday" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="5 日漲跌" field="change5" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="10 日漲跌" field="change10" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="30 日漲跌" field="change30" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="成交量" field="volume" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="週轉率" field="turnover" current={sort} direction={sortDirection} onSort={chooseSort}/><SortHeader label="20MA 乖離" field="ma20" current={sort} direction={sortDirection} onSort={chooseSort}/></tr></thead><tbody>{filtered.map(({stock,tradingDays,change5,change10,change30,ma20Deviation})=>{const turnover=stock.volume!==null&&stock.issuedShares!=null&&stock.issuedShares>0?stock.volume/stock.issuedShares*100:null;return <tr key={stock.code}><td><a className="stock-link" href={`#/stocks/${stock.code}`}><b>{stock.code}</b> {stock.name}<small>{stock.market==='TPEX'?'上櫃':'上市'}</small></a></td><td>{industryName(stock.industry)||'未分類'}</td><td className="number">{price(stock.close)}</td><td className={`number ${(stock.changePercent||0)>0?'up':(stock.changePercent||0)<0?'down':'muted'}`}>{pct(stock.changePercent)}</td><td className={`number ${change5===null?'muted':change5>0?'up':change5<0?'down':''}`}>{pct(change5)}</td><td className={`number ${change10===null?'muted':change10>0?'up':change10<0?'down':''}`}>{pct(change10)}</td><td className={`number ${change30===null?'muted':change30>0?'up':change30<0?'down':''}`}>{pct(change30)}<small>{tradingDays} 個有效交易日</small></td><td className="number">{stock.volume===null?'—':`${fmt(stock.volume/1000,0)} 張`}</td><td className="number">{pct(turnover)}</td><td className={`number ${ma20Deviation===null?'muted':ma20Deviation>0?'up':ma20Deviation<0?'down':''}`}>{pct(ma20Deviation)}</td></tr>})}</tbody></table></div>
   {!filtered.length&&<div className="empty-state"><Search size={28}/><h3>沒有符合條件的股票</h3><p>放寬漲跌幅、價格或成交量條件再試一次。</p></div>}
   <div className="table-bottom"><span>行情截至 {shortDate(snapshot.asOf)} · 共 {filtered.length} 檔</span><span>缺少歷史收盤資料的股票不會被當作 0% 納入有門檻的篩選</span></div>
  </section>
  <p className="screener-disclaimer">30 日漲跌幅需要 31 個有效收盤價。當資料期數不足時仍可出現在未設定 30 日門檻的結果中，但該欄會標示「資料不足」。篩選結果僅供研究參考。</p>
 </SiteShell>;
}
