'use client';
import {lazy,Suspense} from 'react';
import {ArrowLeft,ArrowUpRight,Calculator,Info} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {SiteShell} from './site-shell';
import type {Stock,MarketSnapshot,Simulation} from '../lib/market-types';
import {forecastDispositionRisk,sixthClauseMinimumShares} from '../lib/rules';
import {displayIntervals,fmt,shortDate,ruleNames} from '../lib/format';
import {dispositionTier,dispositionTierLabel} from '../lib/disposition-tier';
import {tradingViewUrl} from '../lib/tradingview-url';

const CandlestickChart=lazy(()=>import('./candlestick-chart').then(module=>({default:module.CandlestickChart})));

export function StockDetail({stock:s,snapshot,initial}:{stock:Stock;snapshot:MarketSnapshot;initial:Simulation}){
 const result=initial;
 const g=result.gate,hasCompleteNoticeHistory=s.noticeHistoryComplete===true,counts=[['第一款連續',g.firstStreak,3],['第 1–8 款連續',g.anyStreak,5],['明日十日窗口已累積',g.nineCount,6],['明日三十日窗口已累積',g.twentyNineCount,12]] as const;
 const chart=s.bars.slice(-30).map(b=>({date:shortDate(b.date),close:b.close}));
 const tier=dispositionTier(s,snapshot.calendar,snapshot.asOf);
 const sixthVolume=sixthClauseMinimumShares(s.issuedShares);
 const nextRisk=forecastDispositionRisk(s,snapshot,1);
 return <SiteShell><a href="#/" className="back-link"><ArrowLeft size={16}/> 返回觀測清單</a><div className="page-heading detail-heading"><div><div className="eyebrow">{s.code} · {s.market==='TPEX'?'上櫃':'上市'}普通股 · 推估{dispositionTierLabel[tier]}</div><h1>{s.name}<span className="badge amber">{s.candidateReason?'官方處置候選':'注意條件觀測'}</span></h1><p>以 {snapshot.asOf} 盤後資料，試算 {result.targetDate} 收盤條件。</p><a className="tradingview-link" href={tradingViewUrl(s.market==='TPEX'?'TPEX':'TWSE',s.code)} target="_blank" rel="noopener noreferrer" aria-label={`在 TradingView 查看 ${s.code} ${s.name} K 線圖`}>K 線圖 <ArrowUpRight size={15}/><span>TradingView</span></a></div><div className="quote-block"><strong>{fmt(s.close)}</strong><span className={(s.changePercent||0)>=0?'up':'down'}>{(s.change||0)>0?'+':''}{fmt(s.change)}（{(s.changePercent||0)>0?'+':''}{fmt(s.changePercent)}%）</span></div></div>
 <div className="gate-grid">{counts.map(([label,n,total])=><div className="gate-card" key={label}><p>{label}</p><strong>{hasCompleteNoticeHistory?n:'—'}<span> / {total} 日</span></strong><div className="thin-progress"><span style={{width:hasCompleteNoticeHistory?`${Math.min(n/total*100,100)}%`:'0%'}}/></div></div>)}</div><p className="fine-print gate-note">{hasCompleteNoticeHistory?'已補抓交易所近 105 日注意公告；十日／三十日視窗會包含不連續注意日，同日多款只計一天。累計僅供觀察，官方候選公告與特殊除外規則優先。':'交易所歷史公告尚未成功完整回填，暫不顯示可能不完整的累計；請以交易所官方候選公告及上方原因為準。'}</p>
 <div className="detail-grid"><div className="detail-main"><section className="panel"><div className="panel-heading"><div><h2>明日收盤／成交量觸發條件</h2><p>行情基準 {result.asOf} 收盤 {fmt(result.reference)} 元 · 預測日 {result.targetDate}</p></div><Calculator size={21}/></div><div className="result-intro"><Info size={18}/><div><strong>{g.official?'本檔已列官方處置候選；仍須符合公告所列適用條件。':'以下列出明日可能再次符合注意條件的明確行情門檻。'}</strong><p>符合注意條件不等於直接處置；需同時滿足累計次數與其他適用規則，並以交易所公告為準。{nextRisk?.days===1?` 依目前累計，若明日新增可計次注意，最快可於 ${nextRisk.date} 列入處置候選（${nextRisk.paths.join('、')}）。`:''}{result.referenceAssumed?' 參考價暫以上一收盤價推估；除權息等情形請核對官方參考價。':' 本次採用自訂參考價。'}</p></div></div>
 <div className="rule-results">{result.rules.map(rule=>{const bands=displayIntervals(rule.intervals);return <article className="rule-result" key={rule.rule}><div className="rule-header"><div><span className="rule-index">0{rule.rule}</span><h3>{rule.label}</h3></div><span className={`badge ${rule.status==='conditional'?'blue':'gray'}`}>{rule.status==='conditional'?'有條件門檻':rule.status==='missing'?'待補資料／驗證':'未達門檻'}</span></div>{bands.length?<div className="intervals trigger-conditions">{bands.map((v,i)=><div key={i}><strong>{v.from===v.to?`明日收盤價 = ${fmt(v.from)} 元`:`明日收盤價 ≥ ${fmt(v.from)} 元，且 ≤ ${fmt(v.to)} 元`}</strong></div>)}</div>:<p className="no-threshold">{rule.reason||'依目前資料與假設，找不到符合此分支的合法收盤價。'}</p>}{rule.rule===6&&<p className="volume-trigger">成交量需同時達到 3,000 張（3,000,000 股）及週轉率 5%：{sixthVolume===null?'最低門檻 = max（3,000,000 股，發行普通股數 × 5%）；已串接每日官方公司基本資料，待本批快照補入該欄位。':`官方發行普通股數 ${fmt(s.issuedShares,0)} 股的 5% 為 ${fmt(s.issuedShares!*0.05,0)} 股，因此明日最低成交量為 ${fmt(sixthVolume,0)} 股（${fmt(sixthVolume/1000,0)} 張）。`}週轉率分母採全體已發行普通股數，董事等持股仍計入分母；符合量價門檻仍須同時符合估值條件。</p>}<details open={rule.status==='conditional'}><summary>其他必要條件與假設</summary><ul>{rule.conditions.map(c=><li key={c}>{c}</li>)}</ul></details></article>})}</div><div className="panel-note"><Info size={16}/><p>第 2 款與第 3–14 款及特殊分支尚未完整計算；未顯示門檻不代表不會觸發。上列價格是注意條件的試算值，不是保證進入處置的價格。</p></div></section>
 <details className="panel stock-candlestick-panel"><summary><span><strong>K 棒圖</strong><small>近 {s.bars.filter(bar=>bar.open!==null&&bar.high!==null&&bar.low!==null&&bar.close!==null).slice(-31).length} 個交易日</small></span><span className="badge gray">展開查看</span></summary><div className="stock-candlestick-content"><Suspense fallback={<div className="empty-state">正在載入圖表…</div>}><CandlestickChart stock={s}/></Suspense></div></details><section className="panel chart-panel"><div className="panel-heading"><div><h2>近期收盤走勢</h2><p>最近 {chart.length} 個已取得交易日 · 原始收盤價</p></div><span className="badge gray">日資料</span></div><div className="price-chart" role="img" aria-label={`${s.name}近期收盤價走勢，最新收盤${s.close}元`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:12,right:24,left:4,bottom:8}}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#315bcc" stopOpacity={.2}/><stop offset="100%" stopColor="#315bcc" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="date" minTickGap={42} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#7a8ba3'}}/><YAxis domain={['auto','auto']} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#7a8ba3'}}/><Tooltip formatter={v=>[fmt(Number(v)),'收盤價']} contentStyle={{borderRadius:8,border:'1px solid #e0e6ef',fontSize:14}}/><Area type="linear" dataKey="close" stroke="#315bcc" strokeWidth={2.5} fill="url(#priceFill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>近期注意紀錄</h2><p>保留官方原因文字，日期與款次可逐筆核對</p></div><a className="text-link" href={s.market==='TPEX'?'https://www.tpex.org.tw/zh-tw/announce/market/attention.html':`https://www.twse.com.tw/announcement/notice?response=html&stockNo=${s.code}`} target="_blank" rel="noreferrer">官方查詢 <ArrowUpRight size={14}/></a></div><div className="notice-history">{s.notices.slice(0,20).map((n,i)=><article key={`${n.date}-${i}`}><div><time>{shortDate(n.date)}</time><span>{n.rules.map(r=>ruleNames[r]).join('、')}</span></div><p>{n.reason}</p></article>)}{!s.notices.length&&<p className="content-padding muted">本批次無注意紀錄。</p>}</div></section>
 {s.dispositions.length>0&&<section className="panel"><div className="panel-heading"><h2>已公告處置紀錄</h2></div><div className="notice-history">{s.dispositions.map((d,i)=><article key={i}><div><time>{d.announced}</time><span>{d.start} — {d.end}</span></div><p>{d.measure}。{d.content}</p></article>)}</div></section>}</div>
 </div></SiteShell>;
}
