'use client';
/* Full document navigation refreshes server snapshots and avoids the observed Vinext client-navigation regression. */
/* eslint-disable @next/next/no-html-link-for-pages */

import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Calculator,Save,RotateCcw,Info,CalendarDays} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Button} from './ui/button';
import {SiteShell} from './site-shell';
import type {Stock,MarketSnapshot,Simulation,Scenario} from '../lib/market-types';
import {DEFAULT_SCENARIO} from '../lib/rules';
import {fmt,shortDate,ruleNames} from '../lib/format';
import {dispositionTier,dispositionTierLabel} from '../lib/disposition-tier';

const fields:[keyof Scenario,string,string][]=[['market6','全市場六日累積漲跌幅','%'],['industry6','同類六日累積漲跌幅','%'],['marketPe','全市場本益比平均','倍'],['marketPb','全市場股價淨值比平均','倍'],['industryPb','同類股價淨值比平均','倍']];
export function StockDetail({stock:s,snapshot,initial}:{stock:Stock;snapshot:MarketSnapshot;initial:Simulation}){
 const [draft,setDraft]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(DEFAULT_SCENARIO).map(([k,v])=>[k,String(v)]))),[reference,setReference]=useState(''),[result,setResult]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 const update=(key:string,value:string)=>{setDraft(old=>({...old,[key]:value}));setDirty(true);};
 async function calculate(save=false){setBusy(true);setMessage('');try{if(Object.values(draft).some(v=>v.trim()===''))throw new Error('請填入完整情境數值。');const scenario=Object.fromEntries(Object.entries(draft).map(([k,v])=>[k,Number(v)]));if(reference.trim())scenario.referencePrice=Number(reference);const response=await fetch('/api/simulations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:s.code,scenario,save})});const body=await response.json() as {result:Simulation;saved:boolean;error?:string;warning?:string};if(!response.ok)throw new Error(body.error||'試算失敗');setResult(body.result);setDirty(false);setMessage(save?(body.saved?'試算已保存，可在「試算紀錄」查閱。':body.warning||'已計算，但保存失敗。'):'已依目前輸入更新試算。');}catch(error){setMessage(error instanceof Error?error.message:'連線未完成');}finally{setBusy(false);}}
 const g=result.gate,counts=[['第一款連續',g.firstStreak,3],['第 1–8 款連續',g.anyStreak,5],['明日十日窗口已累積',g.nineCount,6],['明日三十日窗口已累積',g.twentyNineCount,12]] as const;
 const chart=s.bars.slice(-30).map(b=>({date:shortDate(b.date),close:b.close}));
 const tier=dispositionTier(s,snapshot.calendar,snapshot.asOf);
 return <SiteShell><a href="/" className="back-link"><ArrowLeft size={16}/> 返回觀測清單</a><div className="page-heading detail-heading"><div><div className="eyebrow">{s.code} · 上市普通股 · 推估{dispositionTierLabel[tier]}</div><h1>{s.name}<span className="badge amber">{s.candidateReason?'官方處置候選':'注意條件觀測'}</span></h1><p>以 {snapshot.asOf} 盤後資料，試算 {result.targetDate} 收盤條件。</p></div><div className="quote-block"><strong>{fmt(s.close)}</strong><span className={(s.changePercent||0)>=0?'up':'down'}>{(s.change||0)>0?'+':''}{fmt(s.change)}（{(s.changePercent||0)>0?'+':''}{fmt(s.changePercent)}%）</span></div></div>
 <div className="gate-grid">{counts.map(([label,n,total])=><div className="gate-card" key={label}><p>{label}</p><strong>{n}<span> / {total} 日</span></strong><div className="thin-progress"><span style={{width:`${Math.min(n/total*100,100)}%`}}/></div></div>)}</div><p className="fine-print gate-note">十日／三十日試算先移除明日到期的一天，顯示已知 9／29 日的計次；同日多款只計一天。一般計次重建尚未套用全部特殊除外，官方候選公告優先。</p>
 <div className="detail-grid"><div className="detail-main"><section className="panel"><div className="panel-heading"><div><h2>下一交易日・條件式價格</h2><p>參考價 {fmt(result.reference)} 元 · 正常價格範圍 {fmt(result.limits.low)} — {fmt(result.limits.high)}</p></div><Calculator size={21}/></div><div className="result-intro"><Info size={18}/><div><strong>{g.official?'官方列入處置候選，仍須再次符合適用注意條件。':'未列入本批官方候選；注意門檻成立不等於明日處置。'}</strong><p>{result.referenceAssumed?'參考價暫以上一收盤價推估；如有除權息、減資，請核對正式參考價。':'本次使用自訂參考價；其適用性仍需核對官方公告。'}</p></div></div>{dirty&&<p className="notice-banner warning" role="status">輸入已變更，下列仍是上次結果；請按「更新試算」。</p>}
 <div className="rule-results">{result.rules.map(rule=><article className="rule-result" key={rule.rule}><div className="rule-header"><div><span className="rule-index">0{rule.rule}</span><h3>{rule.label}</h3></div><span className={`badge ${rule.status==='conditional'?'blue':'gray'}`}>{rule.status==='conditional'?'有條件區間':rule.status==='missing'?'待補資料／驗證':'此情境無區間'}</span></div>{rule.intervals.length?<div className="intervals">{rule.intervals.map((v,i)=><div key={i}><strong>{fmt(v.from)}{v.to===v.from?'':` — ${fmt(v.to)}`}</strong><span>元 · {v.direction==='up'?'參考價以上':'參考價以下'}</span></div>)}</div>:<p className="no-threshold">{rule.reason||'正常漲跌幅內，未找到符合此分支的合法升降單位價格。'}</p>}<details open={rule.status==='conditional'}><summary>必須同時成立的條件</summary><ul>{rule.conditions.map(c=><li key={c}>{c}</li>)}</ul></details></article>)}</div><div className="panel-note"><Info size={16}/><p>未涵蓋的款次仍可能導致注意或處置；此頁不提供確定處置價格或機率。</p></div></section>
 <section className="panel chart-panel"><div className="panel-heading"><div><h2>近期收盤走勢</h2><p>最近 {chart.length} 個已取得交易日 · 原始收盤價</p></div><span className="badge gray">日資料</span></div><div className="price-chart" role="img" aria-label={`${s.name}近期收盤價走勢，最新收盤${s.close}元`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:12,right:24,left:4,bottom:8}}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#315bcc" stopOpacity={.2}/><stop offset="100%" stopColor="#315bcc" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="date" minTickGap={42} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#7a8ba3'}}/><YAxis domain={['auto','auto']} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#7a8ba3'}}/><Tooltip formatter={v=>[fmt(Number(v)),'收盤價']} contentStyle={{borderRadius:8,border:'1px solid #e0e6ef',fontSize:14}}/><Area type="linear" dataKey="close" stroke="#315bcc" strokeWidth={2.5} fill="url(#priceFill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>近期注意紀錄</h2><p>保留官方原因文字，日期與款次可逐筆核對</p></div><a className="text-link" href={`https://www.twse.com.tw/announcement/notice?response=html&stockNo=${s.code}`} target="_blank" rel="noreferrer">官方查詢 <ArrowUpRight size={14}/></a></div><div className="notice-history">{s.notices.slice(0,20).map((n,i)=><article key={`${n.date}-${i}`}><div><time>{shortDate(n.date)}</time><span>{n.rules.map(r=>ruleNames[r]).join('、')}</span></div><p>{n.reason}</p></article>)}{!s.notices.length&&<p className="content-padding muted">本批次無注意紀錄。</p>}</div></section>
 {s.dispositions.length>0&&<section className="panel"><div className="panel-heading"><h2>已公告處置紀錄</h2></div><div className="notice-history">{s.dispositions.map((d,i)=><article key={i}><div><time>{d.announced}</time><span>{d.start} — {d.end}</span></div><p>{d.measure}。{d.content}</p></article>)}</div></section>}</div>
 <aside className="scenario-panel panel"><div className="panel-heading"><div><div className="eyebrow">SCENARIO LAB</div><h2>調整試算情境</h2></div><Calculator size={20}/></div><form onSubmit={e=>{e.preventDefault();void calculate();}}><div className="scenario-note">以下是可編輯的假設，<strong>並非官方市場／產業平均值</strong>。改變假設，價格區間也會變動。</div><label className="number-field"><span>下一交易日參考價</span><div><input type="number" min="0.01" max="1000000" step="0.01" value={reference} placeholder={String(s.close)} onChange={e=>{setReference(e.target.value);setDirty(true);}}/><span>元</span></div><small>留白使用當日收盤價</small></label>{fields.map(([key,label,unit])=><label className="number-field" key={key}><span>{label}</span><div><input type="number" step="any" min={key.includes('6')?-1000:0.01} max="1000" required value={draft[key]} onChange={e=>update(key,e.target.value)}/><span>{unit}</span></div></label>)}<Button className="calculate-button" type="submit" disabled={busy}><Calculator size={16}/>{busy?'處理中…':'更新試算'}</Button><Button className="save-button" variant="outline" type="button" disabled={busy} onClick={()=>void calculate(true)}><Save size={16}/> 試算並保存</Button><button className="reset-button" type="button" onClick={()=>{setDraft(Object.fromEntries(Object.entries(DEFAULT_SCENARIO).map(([k,v])=>[k,String(v)])));setReference('');setDirty(true);}}><RotateCcw size={13}/> 還原預設假設</button>{message&&<p className="form-message" role="status">{message}</p>}</form><div className="scenario-meta"><div><span>行情日期</span><strong>{snapshot.asOf}</strong></div><div><span>規則版本</span><strong>{result.rulesVersion}</strong></div><div><span>本益比／淨值比</span><strong>{fmt(s.pe)} / {fmt(s.pb)}</strong></div></div><div className="panel-note"><CalendarDays size={16}/><p>若 {result.targetDate} 收盤後公告，依公告可能自 {result.effectiveDate} 起執行。</p></div></aside></div></SiteShell>;
}
